export declare const pairs: {
    "BTC/USD": string;
    "ETH/USD": string;
    "LINK/USD": string;
    "DOGE/USD": string;
    "MATIC/USD": string;
    "ADA/USD": string;
    "SUSHI/USD": string;
    "AAVE/USD": string;
    "ALGO/USD": string;
    "BAT/USD": string;
    "COMP/USD": string;
    "DOT/USD": string;
    "EOS/USD": string;
    "LTC/USD": string;
    "MANA/USD": string;
    "OMG/USD": string;
    "SNX/USD": string;
    "UNI/USD": string;
    "XLM/USD": string;
    "XRP/USD": string;
    "ZEC/USD": string;
    "EUR/USD": string;
    "USD/JPY": string;
    "GBP/USD": string;
    "USD/CHF": string;
    "AUD/USD": string;
    "USD/CAD": string;
    "NZD/USD": string;
    "EUR/CHF": string;
    "EUR/JPY": string;
    "EUR/GBP": string;
    "LUNA/USD": string;
    "YFI/USD": string;
    "SOL/USD": string;
    "XTZ/USD": string;
    "BCH/USD": string;
    "BNT/USD": string;
    "CRV/USD": string;
    "DASH/USD": string;
    "ETC/USD": string;
    "ICP/USD": string;
    "MKR/USD": string;
    "NEO/USD": string;
    "THETA/USD": string;
    "TRX/USD": string;
    "ZRX/USD": string;
    "SAND/USD": string;
    "BNB/USD": string;
    "AXS/USD": string;
    "GRT/USD": string;
    "HBAR/USD": string;
    "XMR/USD": string;
    "ENJ/USD": string;
    "FTM/USD": string;
    "FTT/USD": string;
    "APE/USD": string;
    "CHZ/USD": string;
    "SHIB/USD": string;
    "AAPL/USD": string;
    "FB/USD": string;
    "GOOGL/USD": string;
    "AMZN/USD": string;
    "MSFT/USD": string;
    "TSLA/USD": string;
    "SNAP/USD": string;
    "NVDA/USD": string;
    "V/USD": string;
    "MA/USD": string;
    "PFE/USD": string;
    "KO/USD": string;
    "DIS/USD": string;
    "GME/USD": string;
    "NKE/USD": string;
    "AMD/USD": string;
    "PYPL/USD": string;
    "ABNB/USD": string;
    "BA/USD": string;
    "SBUX/USD": string;
    "WMT/USD": string;
    "INTC/USD": string;
    "MCD/USD": string;
    "META/USD": string;
    "GOOGL_1/USD": string;
    "GME_1/USD": string;
    "AMZN_1/USD": string;
    "TSLA_1/USD": string;
    "SPY/USD": string;
    "QQQ/USD": string;
    "IWM/USD": string;
    "DIA/USD": string;
    "XAU/USD": string;
    "XAG/USD": string;
    "USD/CNH": string;
    "USD/SGD": string;
    "EUR/SEK": string;
    "USD/KRW": string;
    "EUR/NOK": string;
    "USD/INR": string;
    "USD/MXN": string;
    "USD/TWD": string;
    "USD/ZAR": string;
    "USD/BRL": string;
    "AVAX/USD": string;
    "ATOM/USD": string;
    "NEAR/USD": string;
    "QNT/USD": string;
    "IOTA/USD": string;
    "TON/USD": string;
    "RPL/USD": string;
    "ARB/USD": string;
};
export declare const getAssetClassFromGroupIndex: (groupIndex: number) => "crypto" | "forex" | "stocks" | "indices" | "commodities" | undefined;
export declare const tickerChanges: {
    FB: {
        newTicker: string;
        date: string;
    };
};
export declare const stockSplits: {
    "AMZN_1/USD": {
        date: string;
        split: number;
    };
    "GOOGL_1/USD": {
        date: string;
        split: number;
    };
    "GME_1/USD": {
        date: string;
        split: number;
    };
    "TSLA_1/USD": {
        date: string;
        split: number;
    };
};
export declare const defaultSpreadReductionsP100: number[];
